/**
 * The exercise catalogue.
 *
 * Every exercise the app knows about lives here, tagged with the muscles it
 * trains so the body map and the "what should I hit" suggestions can work off
 * whatever routine the user has built.
 *
 * IMPORTANT: ids are persisted inside workout logs. Never rename an existing
 * id — add a new entry instead.
 *
 * GIFs: entries that ship with a `gifUrl` use a known-good static URL. The rest
 * resolve a GIF lazily at runtime (see `lib/gifs.ts`) and fall back to a drawn
 * muscle illustration, so an exercise is always usable even with no animation.
 */

import type { MuscleId } from "./muscles";

export type Equipment =
  | "barbell"
  | "dumbbell"
  | "machine"
  | "cable"
  | "bodyweight"
  | "kettlebell"
  | "band"
  | "smith";

export type ExerciseGroup = "legs" | "push" | "pull" | "core" | "neck" | "cardio";

export interface LibraryExercise {
  id: string;
  name: string;
  /** Human-readable muscle blurb shown on the exercise card. */
  muscle: string;
  primary: MuscleId[];
  secondary: MuscleId[];
  equipment: Equipment;
  group: ExerciseGroup;
  gifUrl?: string;
  defaultSets: number;
  defaultRepsMin: number;
  defaultRepsMax: number;
}

const S = { defaultSets: 3, defaultRepsMin: 8, defaultRepsMax: 12 } as const;
const HEAVY = { defaultSets: 3, defaultRepsMin: 6, defaultRepsMax: 8 } as const;
const HIGH = { defaultSets: 3, defaultRepsMin: 12, defaultRepsMax: 20 } as const;

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  // ------------------------------------------------------------------ LEGS
  {
    id: "barbell-squat",
    name: "Barbell Squats",
    muscle: "Quads & Glutes",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "lower-back", "abs"],
    equipment: "barbell",
    group: "legs",
    gifUrl: "https://static.exercisedb.dev/media/s7HX1BY.gif",
    ...HEAVY,
  },
  {
    id: "romanian-deadlift",
    name: "Romanian Deadlifts",
    muscle: "Hamstrings & Glutes",
    primary: ["hamstrings", "glutes"],
    secondary: ["lower-back", "forearms"],
    equipment: "barbell",
    group: "legs",
    gifUrl: "https://static.exercisedb.dev/media/wQ2c4XD.gif",
    ...HEAVY,
  },
  {
    id: "leg-press",
    name: "Leg Press",
    muscle: "Quads & Glutes",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: "machine",
    group: "legs",
    gifUrl: "https://static.exercisedb.dev/media/2Qh2J1e.gif",
    ...S,
  },
  {
    id: "leg-extension",
    name: "Leg Extensions",
    muscle: "Quads",
    primary: ["quads"],
    secondary: [],
    equipment: "machine",
    group: "legs",
    gifUrl: "https://static.exercisedb.dev/media/my33uHU.gif",
    ...S,
  },
  {
    id: "leg-curl",
    name: "Seated Leg Curls",
    muscle: "Hamstrings",
    primary: ["hamstrings"],
    secondary: ["calves"],
    equipment: "machine",
    group: "legs",
    gifUrl: "https://static.exercisedb.dev/media/Zg3XY7P.gif",
    ...S,
  },
  {
    id: "barbell-hip-thrust",
    name: "Barbell Hip Thrusts",
    muscle: "Glutes",
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: "barbell",
    group: "legs",
    gifUrl: "https://static.exercisedb.dev/media/qKBpF7I.gif",
    ...S,
  },
  {
    id: "seated-calf-raise",
    name: "Seated Calf Raises",
    muscle: "Calves (Soleus)",
    primary: ["calves"],
    secondary: [],
    equipment: "machine",
    group: "legs",
    gifUrl: "https://static.exercisedb.dev/media/bOOdeyc.gif",
    ...S,
  },
  {
    id: "front-squat",
    name: "Front Squats",
    muscle: "Quads",
    primary: ["quads"],
    secondary: ["glutes", "abs", "upper-back"],
    equipment: "barbell",
    group: "legs",
    ...HEAVY,
  },
  {
    id: "hack-squat",
    name: "Hack Squats",
    muscle: "Quads",
    primary: ["quads"],
    secondary: ["glutes"],
    equipment: "machine",
    group: "legs",
    ...S,
  },
  {
    id: "goblet-squat",
    name: "Goblet Squats",
    muscle: "Quads & Glutes",
    primary: ["quads", "glutes"],
    secondary: ["abs"],
    equipment: "dumbbell",
    group: "legs",
    ...S,
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squats",
    muscle: "Quads & Glutes",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings"],
    equipment: "dumbbell",
    group: "legs",
    ...S,
  },
  {
    id: "walking-lunge",
    name: "Walking Lunges",
    muscle: "Quads & Glutes",
    primary: ["quads", "glutes"],
    secondary: ["hamstrings", "calves", "adductors"],
    equipment: "dumbbell",
    group: "legs",
    ...S,
  },
  {
    id: "reverse-lunge",
    name: "Reverse Lunges",
    muscle: "Glutes & Quads",
    primary: ["glutes", "quads"],
    secondary: ["hamstrings"],
    equipment: "dumbbell",
    group: "legs",
    ...S,
  },
  {
    id: "step-up",
    name: "Dumbbell Step-Ups",
    muscle: "Quads & Glutes",
    primary: ["quads", "glutes"],
    secondary: ["calves"],
    equipment: "dumbbell",
    group: "legs",
    ...S,
  },
  {
    id: "conventional-deadlift",
    name: "Conventional Deadlifts",
    muscle: "Posterior Chain",
    primary: ["hamstrings", "glutes", "lower-back"],
    secondary: ["traps", "lats", "forearms", "quads"],
    equipment: "barbell",
    group: "legs",
    ...HEAVY,
  },
  {
    id: "sumo-deadlift",
    name: "Sumo Deadlifts",
    muscle: "Glutes & Quads",
    primary: ["glutes", "quads", "hamstrings"],
    secondary: ["lower-back", "traps", "forearms", "adductors"],
    equipment: "barbell",
    group: "legs",
    ...HEAVY,
  },
  {
    id: "stiff-leg-deadlift",
    name: "Stiff-Leg Deadlifts",
    muscle: "Hamstrings",
    primary: ["hamstrings"],
    secondary: ["glutes", "lower-back"],
    equipment: "dumbbell",
    group: "legs",
    ...S,
  },
  {
    id: "lying-leg-curl",
    name: "Lying Leg Curls",
    muscle: "Hamstrings",
    primary: ["hamstrings"],
    secondary: ["calves"],
    equipment: "machine",
    group: "legs",
    ...S,
  },
  {
    id: "nordic-curl",
    name: "Nordic Hamstring Curls",
    muscle: "Hamstrings",
    primary: ["hamstrings"],
    secondary: ["glutes"],
    equipment: "bodyweight",
    group: "legs",
    defaultSets: 3,
    defaultRepsMin: 5,
    defaultRepsMax: 10,
  },
  {
    id: "good-morning",
    name: "Good Mornings",
    muscle: "Hamstrings & Lower Back",
    primary: ["hamstrings", "lower-back"],
    secondary: ["glutes"],
    equipment: "barbell",
    group: "legs",
    ...S,
  },
  {
    id: "cable-pull-through",
    name: "Cable Pull-Throughs",
    muscle: "Glutes",
    primary: ["glutes"],
    secondary: ["hamstrings", "lower-back"],
    equipment: "cable",
    group: "legs",
    ...S,
  },
  {
    id: "glute-kickback",
    name: "Cable Glute Kickbacks",
    muscle: "Glutes",
    primary: ["glutes"],
    secondary: ["hamstrings"],
    equipment: "cable",
    group: "legs",
    ...S,
  },
  {
    id: "hip-abduction",
    name: "Hip Abduction Machine",
    muscle: "Glute Medius",
    primary: ["glutes"],
    secondary: [],
    equipment: "machine",
    group: "legs",
    ...HIGH,
  },
  {
    id: "standing-calf-raise",
    name: "Standing Calf Raises",
    muscle: "Calves (Gastroc)",
    primary: ["calves"],
    secondary: [],
    equipment: "machine",
    group: "legs",
    ...HIGH,
  },
  {
    id: "leg-press-calf-raise",
    name: "Leg Press Calf Raises",
    muscle: "Calves",
    primary: ["calves"],
    secondary: [],
    equipment: "machine",
    group: "legs",
    ...HIGH,
  },
  {
    id: "db-calf-raise",
    name: "Single-Leg DB Calf Raise",
    muscle: "Calves",
    primary: ["calves"],
    secondary: [],
    equipment: "dumbbell",
    group: "legs",
    ...HIGH,
  },

  // ------------------------------------------------------------------ PUSH
  {
    id: "barbell-bench-press",
    name: "Barbell Bench Press",
    muscle: "Chest",
    primary: ["chest"],
    secondary: ["triceps", "front-delts"],
    equipment: "barbell",
    group: "push",
    gifUrl: "https://static.exercisedb.dev/media/EIeI8Vf.gif",
    ...HEAVY,
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    muscle: "Upper Chest",
    primary: ["chest", "front-delts"],
    secondary: ["triceps"],
    equipment: "dumbbell",
    group: "push",
    gifUrl: "https://static.exercisedb.dev/media/ns0SIbU.gif",
    ...S,
  },
  {
    id: "cable-crossover",
    name: "Cable Crossovers",
    muscle: "Chest (Isolation)",
    primary: ["chest"],
    secondary: ["front-delts"],
    equipment: "cable",
    group: "push",
    gifUrl: "https://static.exercisedb.dev/media/0CXGHya.gif",
    ...S,
  },
  {
    id: "seated-shoulder-press",
    name: "Seated DB Shoulder Press",
    muscle: "Front Delts",
    primary: ["front-delts"],
    secondary: ["side-delts", "triceps"],
    equipment: "dumbbell",
    group: "push",
    gifUrl: "https://static.exercisedb.dev/media/znQUdHY.gif",
    ...S,
  },
  {
    id: "db-lateral-raise",
    name: "DB Lateral Raises",
    muscle: "Side Delts",
    primary: ["side-delts"],
    secondary: ["traps"],
    equipment: "dumbbell",
    group: "push",
    gifUrl: "https://static.exercisedb.dev/media/DsgkuIt.gif",
    ...S,
  },
  {
    id: "front-db-raise",
    name: "Dumbbell Shoulder Shrugs",
    muscle: "Traps",
    primary: ["traps"],
    secondary: ["forearms"],
    equipment: "dumbbell",
    group: "push",
    gifUrl: "https://fitnessprogramer.com/wp-content/uploads/2021/04/Dumbbell-Shrug.gif",
    ...S,
  },
  {
    id: "cable-overhead-tricep",
    name: "Rope Tricep Extension",
    muscle: "Tricep Long Head",
    primary: ["triceps"],
    secondary: [],
    equipment: "cable",
    group: "push",
    gifUrl: "https://fitnessprogramer.com/wp-content/uploads/2021/06/Rope-Pushdown.gif",
    ...S,
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Rope Pushdowns",
    muscle: "Tricep Lateral Head",
    primary: ["triceps"],
    secondary: [],
    equipment: "cable",
    group: "push",
    gifUrl: "https://static.exercisedb.dev/media/3ZflifB.gif",
    ...S,
  },
  {
    id: "overhead-tricep-ext",
    name: "Overhead DB Tricep Ext.",
    muscle: "Tricep (Stretch)",
    primary: ["triceps"],
    secondary: [],
    equipment: "dumbbell",
    group: "push",
    gifUrl: "https://static.exercisedb.dev/media/kont8Ut.gif",
    ...S,
  },
  {
    id: "incline-barbell-press",
    name: "Incline Barbell Press",
    muscle: "Upper Chest",
    primary: ["chest", "front-delts"],
    secondary: ["triceps"],
    equipment: "barbell",
    group: "push",
    ...HEAVY,
  },
  {
    id: "decline-bench-press",
    name: "Decline Bench Press",
    muscle: "Lower Chest",
    primary: ["chest"],
    secondary: ["triceps"],
    equipment: "barbell",
    group: "push",
    ...S,
  },
  {
    id: "flat-db-press",
    name: "Flat Dumbbell Press",
    muscle: "Chest",
    primary: ["chest"],
    secondary: ["triceps", "front-delts"],
    equipment: "dumbbell",
    group: "push",
    ...S,
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    muscle: "Chest",
    primary: ["chest"],
    secondary: ["triceps", "front-delts"],
    equipment: "machine",
    group: "push",
    ...S,
  },
  {
    id: "pec-deck",
    name: "Pec Deck Flyes",
    muscle: "Chest (Isolation)",
    primary: ["chest"],
    secondary: ["front-delts"],
    equipment: "machine",
    group: "push",
    ...S,
  },
  {
    id: "db-fly",
    name: "Dumbbell Flyes",
    muscle: "Chest (Stretch)",
    primary: ["chest"],
    secondary: ["front-delts"],
    equipment: "dumbbell",
    group: "push",
    ...S,
  },
  {
    id: "low-to-high-cable-fly",
    name: "Low-to-High Cable Fly",
    muscle: "Upper Chest",
    primary: ["chest"],
    secondary: ["front-delts"],
    equipment: "cable",
    group: "push",
    ...S,
  },
  {
    id: "push-up",
    name: "Push-Ups",
    muscle: "Chest",
    primary: ["chest"],
    secondary: ["triceps", "front-delts", "abs", "serratus"],
    equipment: "bodyweight",
    group: "push",
    ...HIGH,
  },
  {
    id: "dips",
    name: "Chest Dips",
    muscle: "Lower Chest & Triceps",
    primary: ["chest", "triceps"],
    secondary: ["front-delts"],
    equipment: "bodyweight",
    group: "push",
    ...S,
  },
  {
    id: "overhead-barbell-press",
    name: "Standing Overhead Press",
    muscle: "Shoulders",
    primary: ["front-delts"],
    secondary: ["side-delts", "triceps", "abs"],
    equipment: "barbell",
    group: "push",
    ...HEAVY,
  },
  {
    id: "arnold-press",
    name: "Arnold Press",
    muscle: "Front & Side Delts",
    primary: ["front-delts", "side-delts"],
    secondary: ["triceps"],
    equipment: "dumbbell",
    group: "push",
    ...S,
  },
  {
    id: "machine-shoulder-press",
    name: "Machine Shoulder Press",
    muscle: "Shoulders",
    primary: ["front-delts"],
    secondary: ["side-delts", "triceps"],
    equipment: "machine",
    group: "push",
    ...S,
  },
  {
    id: "cable-lateral-raise",
    name: "Cable Lateral Raises",
    muscle: "Side Delts",
    primary: ["side-delts"],
    secondary: [],
    equipment: "cable",
    group: "push",
    ...HIGH,
  },
  {
    id: "machine-lateral-raise",
    name: "Machine Lateral Raises",
    muscle: "Side Delts",
    primary: ["side-delts"],
    secondary: [],
    equipment: "machine",
    group: "push",
    ...HIGH,
  },
  {
    id: "front-plate-raise",
    name: "Front Plate Raises",
    muscle: "Front Delts",
    primary: ["front-delts"],
    secondary: [],
    equipment: "barbell",
    group: "push",
    ...S,
  },
  {
    id: "upright-row",
    name: "Cable Upright Rows",
    muscle: "Side Delts & Traps",
    primary: ["side-delts", "traps"],
    secondary: ["biceps"],
    equipment: "cable",
    group: "push",
    ...S,
  },
  {
    id: "barbell-shrug",
    name: "Barbell Shrugs",
    muscle: "Traps",
    primary: ["traps"],
    secondary: ["forearms", "neck"],
    equipment: "barbell",
    group: "push",
    ...S,
  },
  {
    id: "skull-crusher",
    name: "Skull Crushers",
    muscle: "Triceps",
    primary: ["triceps"],
    secondary: [],
    equipment: "barbell",
    group: "push",
    ...S,
  },
  {
    id: "close-grip-bench",
    name: "Close-Grip Bench Press",
    muscle: "Triceps & Chest",
    primary: ["triceps"],
    secondary: ["chest", "front-delts"],
    equipment: "barbell",
    group: "push",
    ...HEAVY,
  },
  {
    id: "bench-dip",
    name: "Bench Dips",
    muscle: "Triceps",
    primary: ["triceps"],
    secondary: ["front-delts"],
    equipment: "bodyweight",
    group: "push",
    ...HIGH,
  },
  {
    id: "single-arm-pushdown",
    name: "Single-Arm Pushdowns",
    muscle: "Triceps",
    primary: ["triceps"],
    secondary: [],
    equipment: "cable",
    group: "push",
    ...S,
  },
  {
    id: "db-kickback",
    name: "Tricep Kickbacks",
    muscle: "Triceps",
    primary: ["triceps"],
    secondary: [],
    equipment: "dumbbell",
    group: "push",
    ...HIGH,
  },

  // ------------------------------------------------------------------ PULL
  {
    id: "barbell-row",
    name: "Barbell Rows",
    muscle: "Back (Thickness)",
    primary: ["lats", "upper-back"],
    secondary: ["biceps", "rear-delts", "lower-back"],
    equipment: "barbell",
    group: "pull",
    gifUrl: "https://static.exercisedb.dev/media/eZyBC3j.gif",
    ...HEAVY,
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldowns",
    muscle: "Back (Width)",
    primary: ["lats"],
    secondary: ["biceps", "upper-back"],
    equipment: "cable",
    group: "pull",
    gifUrl: "https://static.exercisedb.dev/media/qdRxqCj.gif",
    ...S,
  },
  {
    id: "seated-cable-row",
    name: "Seated Cable Rows",
    muscle: "Mid-Back",
    primary: ["upper-back", "lats"],
    secondary: ["biceps", "rear-delts"],
    equipment: "cable",
    group: "pull",
    gifUrl: "https://static.exercisedb.dev/media/fUBheHs.gif",
    ...S,
  },
  {
    id: "straight-arm-pulldown",
    name: "Straight Arm Pulldowns",
    muscle: "Lats (Isolation)",
    primary: ["lats"],
    secondary: ["triceps"],
    equipment: "cable",
    group: "pull",
    gifUrl: "https://static.exercisedb.dev/media/x69MAlq.gif",
    ...S,
  },
  {
    id: "face-pull",
    name: "Face Pulls",
    muscle: "Rear Delts / Posture",
    primary: ["rear-delts", "upper-back"],
    secondary: ["traps"],
    equipment: "cable",
    group: "pull",
    gifUrl: "https://static.exercisedb.dev/media/wqNPGCg.gif",
    ...S,
  },
  {
    id: "single-arm-db-row",
    name: "Rear Delt Fly",
    muscle: "Rear Delts",
    primary: ["rear-delts"],
    secondary: ["upper-back"],
    equipment: "dumbbell",
    group: "pull",
    gifUrl: "https://gymvisual.com/img/p/1/8/3/6/8/18368.gif",
    ...S,
  },
  {
    id: "dumbbell-bicep-curl",
    name: "Dumbbell Bicep Curls",
    muscle: "Biceps",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "dumbbell",
    group: "pull",
    gifUrl: "https://static.exercisedb.dev/media/NbVPDMW.gif",
    ...S,
  },
  {
    id: "preacher-curl",
    name: "Preacher Curls",
    muscle: "Bicep Peak",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "barbell",
    group: "pull",
    gifUrl: "https://static.exercisedb.dev/media/jivWf8n.gif",
    ...S,
  },
  {
    id: "hammer-curl",
    name: "Hammer Curls",
    muscle: "Forearms & Biceps",
    primary: ["biceps", "forearms"],
    secondary: [],
    equipment: "dumbbell",
    group: "pull",
    gifUrl: "https://static.exercisedb.dev/media/slDvUAU.gif",
    ...S,
  },
  {
    id: "pull-up",
    name: "Pull-Ups",
    muscle: "Back (Width)",
    primary: ["lats"],
    secondary: ["biceps", "upper-back", "forearms"],
    equipment: "bodyweight",
    group: "pull",
    ...HEAVY,
  },
  {
    id: "chin-up",
    name: "Chin-Ups",
    muscle: "Lats & Biceps",
    primary: ["lats", "biceps"],
    secondary: ["upper-back"],
    equipment: "bodyweight",
    group: "pull",
    ...HEAVY,
  },
  {
    id: "pendlay-row",
    name: "Pendlay Rows",
    muscle: "Upper Back",
    primary: ["upper-back", "lats"],
    secondary: ["rear-delts", "biceps", "lower-back"],
    equipment: "barbell",
    group: "pull",
    ...HEAVY,
  },
  {
    id: "t-bar-row",
    name: "T-Bar Rows",
    muscle: "Back (Thickness)",
    primary: ["upper-back", "lats"],
    secondary: ["biceps", "rear-delts"],
    equipment: "barbell",
    group: "pull",
    ...S,
  },
  {
    id: "one-arm-db-row",
    name: "One-Arm Dumbbell Rows",
    muscle: "Lats",
    primary: ["lats", "upper-back"],
    secondary: ["biceps", "rear-delts"],
    equipment: "dumbbell",
    group: "pull",
    ...S,
  },
  {
    id: "chest-supported-row",
    name: "Chest-Supported Rows",
    muscle: "Mid-Back",
    primary: ["upper-back"],
    secondary: ["lats", "rear-delts", "biceps"],
    equipment: "machine",
    group: "pull",
    ...S,
  },
  {
    id: "inverted-row",
    name: "Inverted Rows",
    muscle: "Mid-Back",
    primary: ["upper-back"],
    secondary: ["lats", "biceps"],
    equipment: "bodyweight",
    group: "pull",
    ...HIGH,
  },
  {
    id: "neutral-grip-pulldown",
    name: "Neutral-Grip Pulldowns",
    muscle: "Lats",
    primary: ["lats"],
    secondary: ["biceps", "upper-back"],
    equipment: "cable",
    group: "pull",
    ...S,
  },
  {
    id: "machine-row",
    name: "Machine Rows",
    muscle: "Mid-Back",
    primary: ["upper-back", "lats"],
    secondary: ["biceps"],
    equipment: "machine",
    group: "pull",
    ...S,
  },
  {
    id: "rear-delt-machine",
    name: "Reverse Pec Deck",
    muscle: "Rear Delts",
    primary: ["rear-delts"],
    secondary: ["upper-back"],
    equipment: "machine",
    group: "pull",
    ...HIGH,
  },
  {
    id: "cable-rear-delt-fly",
    name: "Cable Rear Delt Flyes",
    muscle: "Rear Delts",
    primary: ["rear-delts"],
    secondary: ["upper-back"],
    equipment: "cable",
    group: "pull",
    ...HIGH,
  },
  {
    id: "shrug-behind-back",
    name: "Behind-the-Back Shrugs",
    muscle: "Traps",
    primary: ["traps"],
    secondary: ["forearms"],
    equipment: "barbell",
    group: "pull",
    ...S,
  },
  {
    id: "back-extension",
    name: "Back Extensions",
    muscle: "Lower Back",
    primary: ["lower-back"],
    secondary: ["glutes", "hamstrings"],
    equipment: "bodyweight",
    group: "pull",
    ...HIGH,
  },
  {
    id: "rack-pull",
    name: "Rack Pulls",
    muscle: "Traps & Lower Back",
    primary: ["traps", "lower-back"],
    secondary: ["lats", "glutes", "forearms"],
    equipment: "barbell",
    group: "pull",
    ...HEAVY,
  },
  {
    id: "barbell-curl",
    name: "Barbell Curls",
    muscle: "Biceps",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "barbell",
    group: "pull",
    ...S,
  },
  {
    id: "ez-bar-curl",
    name: "EZ-Bar Curls",
    muscle: "Biceps",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "barbell",
    group: "pull",
    ...S,
  },
  {
    id: "incline-db-curl",
    name: "Incline Dumbbell Curls",
    muscle: "Bicep Long Head",
    primary: ["biceps"],
    secondary: [],
    equipment: "dumbbell",
    group: "pull",
    ...S,
  },
  {
    id: "concentration-curl",
    name: "Concentration Curls",
    muscle: "Bicep Peak",
    primary: ["biceps"],
    secondary: [],
    equipment: "dumbbell",
    group: "pull",
    ...S,
  },
  {
    id: "cable-curl",
    name: "Cable Curls",
    muscle: "Biceps",
    primary: ["biceps"],
    secondary: ["forearms"],
    equipment: "cable",
    group: "pull",
    ...S,
  },
  {
    id: "spider-curl",
    name: "Spider Curls",
    muscle: "Biceps (Short Head)",
    primary: ["biceps"],
    secondary: [],
    equipment: "dumbbell",
    group: "pull",
    ...S,
  },
  {
    id: "reverse-curl",
    name: "Reverse Curls",
    muscle: "Forearms",
    primary: ["forearms"],
    secondary: ["biceps"],
    equipment: "barbell",
    group: "pull",
    ...S,
  },
  {
    id: "wrist-curl",
    name: "Wrist Curls",
    muscle: "Forearm Flexors",
    primary: ["forearms"],
    secondary: [],
    equipment: "dumbbell",
    group: "pull",
    ...HIGH,
  },
  {
    id: "farmers-walk",
    name: "Farmer's Walks",
    muscle: "Forearms & Traps",
    primary: ["forearms", "traps"],
    secondary: ["abs", "glutes"],
    equipment: "dumbbell",
    group: "pull",
    defaultSets: 3,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },

  // ------------------------------------------------------------------ CORE
  {
    id: "decline-crunch",
    name: "Decline Crunches",
    muscle: "Lower Abs",
    primary: ["abs"],
    secondary: ["obliques"],
    equipment: "bodyweight",
    group: "core",
    gifUrl: "https://static.exercisedb.dev/media/9Ap7miY.gif",
    ...S,
  },
  {
    id: "cable-crunch",
    name: "Cable Crunches",
    muscle: "Upper Abs",
    primary: ["abs"],
    secondary: ["obliques"],
    equipment: "cable",
    group: "core",
    gifUrl: "https://static.exercisedb.dev/media/WW95auq.gif",
    ...S,
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raises",
    muscle: "Lower Abs",
    primary: ["abs"],
    secondary: ["obliques", "forearms"],
    equipment: "bodyweight",
    group: "core",
    ...S,
  },
  {
    id: "captains-chair-raise",
    name: "Captain's Chair Leg Raise",
    muscle: "Lower Abs",
    primary: ["abs"],
    secondary: ["obliques"],
    equipment: "bodyweight",
    group: "core",
    ...S,
  },
  {
    id: "plank",
    name: "Plank",
    muscle: "Core",
    primary: ["abs"],
    secondary: ["obliques", "lower-back"],
    equipment: "bodyweight",
    group: "core",
    defaultSets: 3,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },
  {
    id: "side-plank",
    name: "Side Plank",
    muscle: "Obliques",
    primary: ["obliques"],
    secondary: ["abs"],
    equipment: "bodyweight",
    group: "core",
    defaultSets: 3,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },
  {
    id: "russian-twist",
    name: "Russian Twists",
    muscle: "Obliques",
    primary: ["obliques"],
    secondary: ["abs"],
    equipment: "dumbbell",
    group: "core",
    ...HIGH,
  },
  {
    id: "cable-woodchop",
    name: "Cable Woodchoppers",
    muscle: "Obliques",
    primary: ["obliques"],
    secondary: ["abs"],
    equipment: "cable",
    group: "core",
    ...S,
  },
  {
    id: "ab-wheel",
    name: "Ab Wheel Rollouts",
    muscle: "Core",
    primary: ["abs"],
    secondary: ["lats", "lower-back", "serratus"],
    equipment: "bodyweight",
    group: "core",
    ...S,
  },
  {
    id: "bicycle-crunch",
    name: "Bicycle Crunches",
    muscle: "Abs & Obliques",
    primary: ["abs", "obliques"],
    secondary: [],
    equipment: "bodyweight",
    group: "core",
    ...HIGH,
  },
  {
    id: "dead-bug",
    name: "Dead Bugs",
    muscle: "Core Stability",
    primary: ["abs"],
    secondary: ["lower-back"],
    equipment: "bodyweight",
    group: "core",
    ...HIGH,
  },
  {
    id: "pallof-press",
    name: "Pallof Press",
    muscle: "Anti-Rotation Core",
    primary: ["obliques"],
    secondary: ["abs"],
    equipment: "cable",
    group: "core",
    ...S,
  },
  {
    id: "weighted-sit-up",
    name: "Weighted Sit-Ups",
    muscle: "Abs",
    primary: ["abs"],
    secondary: ["obliques"],
    equipment: "dumbbell",
    group: "core",
    ...S,
  },
  {
    id: "hyperextension-hold",
    name: "Superman Holds",
    muscle: "Lower Back",
    primary: ["lower-back"],
    secondary: ["glutes"],
    equipment: "bodyweight",
    group: "core",
    defaultSets: 3,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },

  // ------------------------------------------------- ADDUCTORS (inner thigh)
  {
    id: "adductor-machine",
    name: "Hip Adduction Machine",
    muscle: "Adductors",
    primary: ["adductors"],
    secondary: [],
    equipment: "machine",
    group: "legs",
    ...HIGH,
  },
  {
    id: "sumo-squat",
    name: "Sumo Squats",
    muscle: "Adductors & Quads",
    primary: ["adductors", "quads"],
    secondary: ["glutes", "hamstrings"],
    equipment: "barbell",
    group: "legs",
    ...S,
  },
  {
    id: "cossack-squat",
    name: "Cossack Squats",
    muscle: "Adductors",
    primary: ["adductors"],
    secondary: ["quads", "glutes"],
    equipment: "bodyweight",
    group: "legs",
    ...S,
  },
  {
    id: "copenhagen-plank",
    name: "Copenhagen Planks",
    muscle: "Adductors",
    primary: ["adductors"],
    secondary: ["obliques", "abs"],
    equipment: "bodyweight",
    group: "legs",
    defaultSets: 3,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },

  // --------------------------------------------------------------- SERRATUS
  {
    id: "db-pullover",
    name: "Dumbbell Pullovers",
    muscle: "Lats & Serratus",
    primary: ["lats", "serratus"],
    secondary: ["chest", "triceps"],
    equipment: "dumbbell",
    group: "pull",
    ...S,
  },
  {
    id: "serratus-punch",
    name: "Cable Serratus Punch",
    muscle: "Serratus Anterior",
    primary: ["serratus"],
    secondary: ["front-delts"],
    equipment: "cable",
    group: "push",
    ...HIGH,
  },
  {
    id: "scapular-push-up",
    name: "Scapular Push-Ups",
    muscle: "Serratus Anterior",
    primary: ["serratus"],
    secondary: ["chest"],
    equipment: "bodyweight",
    group: "push",
    ...HIGH,
  },

  // ------------------------------------------------------------- TIBIALIS
  {
    id: "tibialis-raise",
    name: "Tibialis Raises",
    muscle: "Tibialis Anterior",
    primary: ["tibialis"],
    secondary: [],
    equipment: "bodyweight",
    group: "legs",
    ...HIGH,
  },
  {
    id: "banded-dorsiflexion",
    name: "Banded Dorsiflexion",
    muscle: "Tibialis Anterior",
    primary: ["tibialis"],
    secondary: [],
    equipment: "band",
    group: "legs",
    ...HIGH,
  },

  // ------------------------------------------------------------------- NECK
  {
    id: "neck-curl",
    name: "Neck Curls",
    muscle: "Neck (Flexors)",
    primary: ["neck"],
    secondary: [],
    equipment: "bodyweight",
    group: "neck",
    ...HIGH,
  },
  {
    id: "neck-extension",
    name: "Neck Extensions",
    muscle: "Neck (Extensors)",
    primary: ["neck"],
    secondary: ["traps"],
    equipment: "bodyweight",
    group: "neck",
    ...HIGH,
  },
  {
    id: "neck-lateral-flexion",
    name: "Lateral Neck Raises",
    muscle: "Neck (Lateral)",
    primary: ["neck"],
    secondary: [],
    equipment: "bodyweight",
    group: "neck",
    ...HIGH,
  },
  {
    id: "neck-harness",
    name: "Neck Harness Extensions",
    muscle: "Neck",
    primary: ["neck"],
    secondary: ["traps"],
    equipment: "machine",
    group: "neck",
    ...S,
  },

  // ----------------------------------- TOPPING UP THE THINLY-COVERED GROUPS
  {
    id: "band-pull-apart",
    name: "Band Pull-Aparts",
    muscle: "Rear Delts",
    primary: ["rear-delts"],
    secondary: ["upper-back", "traps"],
    equipment: "band",
    group: "pull",
    ...HIGH,
  },
  {
    id: "prone-rear-delt-raise",
    name: "Prone Incline Rear Delt Raise",
    muscle: "Rear Delts",
    primary: ["rear-delts"],
    secondary: ["upper-back"],
    equipment: "dumbbell",
    group: "pull",
    ...S,
  },
  {
    id: "lean-away-lateral-raise",
    name: "Leaning Cable Lateral Raise",
    muscle: "Side Delts",
    primary: ["side-delts"],
    secondary: [],
    equipment: "cable",
    group: "push",
    ...S,
  },
  {
    id: "donkey-calf-raise",
    name: "Donkey Calf Raises",
    muscle: "Calves (Gastroc)",
    primary: ["calves"],
    secondary: [],
    equipment: "machine",
    group: "legs",
    ...HIGH,
  },
  {
    id: "smith-calf-raise",
    name: "Smith Machine Calf Raises",
    muscle: "Calves",
    primary: ["calves"],
    secondary: [],
    equipment: "smith",
    group: "legs",
    ...HIGH,
  },
  {
    id: "reverse-wrist-curl",
    name: "Reverse Wrist Curls",
    muscle: "Forearm Extensors",
    primary: ["forearms"],
    secondary: [],
    equipment: "dumbbell",
    group: "pull",
    ...HIGH,
  },
  {
    id: "plate-pinch",
    name: "Plate Pinch Holds",
    muscle: "Grip & Forearms",
    primary: ["forearms"],
    secondary: [],
    equipment: "barbell",
    group: "pull",
    defaultSets: 3,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },
  {
    id: "landmine-press",
    name: "Landmine Press",
    muscle: "Shoulders & Upper Chest",
    primary: ["front-delts"],
    secondary: ["chest", "triceps", "serratus"],
    equipment: "barbell",
    group: "push",
    ...S,
  },
  {
    id: "meadows-row",
    name: "Meadows Rows",
    muscle: "Lats & Upper Back",
    primary: ["lats", "upper-back"],
    secondary: ["biceps", "rear-delts"],
    equipment: "barbell",
    group: "pull",
    ...S,
  },
  {
    id: "seal-row",
    name: "Seal Rows",
    muscle: "Mid-Back",
    primary: ["upper-back"],
    secondary: ["lats", "rear-delts", "biceps"],
    equipment: "barbell",
    group: "pull",
    ...S,
  },

  // ---------------------------------------------------------------- CARDIO
  {
    id: "liss-treadmill",
    name: "LISS Treadmill Walk",
    muscle: "Conditioning",
    primary: [],
    secondary: ["calves", "quads"],
    equipment: "machine",
    group: "cardio",
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },
  {
    id: "stairmaster",
    name: "StairMaster",
    muscle: "Conditioning",
    primary: [],
    secondary: ["glutes", "quads", "calves"],
    equipment: "machine",
    group: "cardio",
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },
  {
    id: "cycling",
    name: "Stationary Bike",
    muscle: "Conditioning",
    primary: [],
    secondary: ["quads", "calves"],
    equipment: "machine",
    group: "cardio",
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },
  {
    id: "rowing-machine",
    name: "Rowing Machine",
    muscle: "Conditioning",
    primary: [],
    secondary: ["lats", "upper-back", "quads"],
    equipment: "machine",
    group: "cardio",
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },
  {
    id: "incline-walk",
    name: "Incline Treadmill Walk",
    muscle: "Conditioning",
    primary: [],
    secondary: ["glutes", "hamstrings", "calves"],
    equipment: "machine",
    group: "cardio",
    defaultSets: 1,
    defaultRepsMin: 1,
    defaultRepsMax: 1,
  },
];

export const EXERCISE_BY_ID: Record<string, LibraryExercise> = Object.fromEntries(
  EXERCISE_LIBRARY.map((e) => [e.id, e])
);

export function getLibraryExercise(id: string): LibraryExercise | undefined {
  return EXERCISE_BY_ID[id];
}

export const EQUIPMENT_LABELS: Record<Equipment, string> = {
  barbell: "Barbell",
  dumbbell: "Dumbbell",
  machine: "Machine",
  cable: "Cable",
  bodyweight: "Bodyweight",
  kettlebell: "Kettlebell",
  band: "Band",
  smith: "Smith Machine",
};

export const GROUP_LABELS: Record<ExerciseGroup, string> = {
  legs: "Legs",
  push: "Push",
  pull: "Pull",
  core: "Core",
  neck: "Neck",
  cardio: "Cardio",
};

/** Exercises that train `muscle`, primaries first. */
export function exercisesForMuscle(muscle: MuscleId): LibraryExercise[] {
  const primary = EXERCISE_LIBRARY.filter((e) => e.primary.includes(muscle));
  const secondary = EXERCISE_LIBRARY.filter(
    (e) => !e.primary.includes(muscle) && e.secondary.includes(muscle)
  );
  return [...primary, ...secondary];
}

/** Free-text + facet search over the library. */
export function searchExercises(opts: {
  query?: string;
  muscles?: MuscleId[];
  equipment?: Equipment[];
  group?: ExerciseGroup | null;
}): LibraryExercise[] {
  const q = opts.query?.trim().toLowerCase() ?? "";
  return EXERCISE_LIBRARY.filter((e) => {
    if (q && !e.name.toLowerCase().includes(q) && !e.muscle.toLowerCase().includes(q)) {
      return false;
    }
    if (opts.group && e.group !== opts.group) return false;
    if (opts.equipment?.length && !opts.equipment.includes(e.equipment)) return false;
    if (opts.muscles?.length) {
      const hit = opts.muscles.some(
        (m) => e.primary.includes(m) || e.secondary.includes(m)
      );
      if (!hit) return false;
    }
    return true;
  });
}
