// Generated by scripts/generate-icons.mjs — do not edit.
//
// A digest of public/icons, hung off the icon URLs as a query string. iOS keys
// home screen icons by URL and will not re-fetch one it already holds, so a
// redrawn icon needs a URL that has never been requested before.
export const ICON_VERSION = "51d62a60c75a2f44";
